<a href="https://colab.research.google.com/github/everjava/sctech/blob/main/Semana_2_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns  # Biblioteca de visualização que possui datasets de estudo embutidos

In [5]:
print("1. Carregando o dataset de estudo diretamente da biblioteca...")
# O método 'load_dataset' traz os dados prontos para uso em formato de tabela
#df = sns.load_dataset('iris')
df = pd.read_csv('sample_data/tabela.csv', sep=';')

1. Carregando o dataset de estudo diretamente da biblioteca...

In [6]:
print("\n--- VISÃO GERAL DOS DADOS ---")
display(df.head(200))

--- VISÃO GERAL DOS DADOS ---

,ID,Nome,Idade,Sexo,Peso,Manchas,Temp.,Num. Inter.,Estado,Diagnóstico
0,123,Marcos,37,M,73,Grandes,"38,0",2,SP,Doente
1,124,Maria,18,F,79,Pequenas,"39,5",4,MG,Saudável
2,125,Antônio,40,M,68,Pequenas,"38,0",0,RS,Doente
3,126,Luiza,18,F,90,Médias,"38,5",11,MG,Doente
4,127,Fábio,50,M,78,Grandes,"37,6",2,PE,Saudável
5,128,Carlos,54,M,56,Pequenas,"38,0",3,RJ,Saudável
6,129,Waldir,72,M,67,Grandes,"39,0",0,AM,Doente
7,130,Hegner,22,M,78,Médias,"38,4",6,GO,Saudável

In [7]:
print("\n2. Separando as Features (X) e o Rótulo (y)...")
# Queremos prever a especie flor
X = df.drop(columns=['Manchas'])

2. Separando as Features (X) e o Rótulo (y)...

In [8]:
print(X)

    ID     Nome  Idade Sexo  Peso Temp.  Num. Inter. Estado Diagnóstico
0  123   Marcos     37    M    73  38,0            2     SP      Doente
1  124    Maria     18    F    79  39,5            4     MG    Saudável
2  125  Antônio     40    M    68  38,0            0     RS      Doente
3  126    Luiza     18    F    90  38,5           11     MG      Doente
4  127    Fábio     50    M    78  37,6            2     PE    Saudável
5  128   Carlos     54    M    56  38,0            3     RJ    Saudável
6  129   Waldir     72    M    67  39,0            0     AM      Doente
7  130   Hegner     22    M    78  38,4            6     GO    Saudável

In [10]:
# y = Apenas a coluna 'tip' (Nosso gabarito)
y = df['Manchas']

In [11]:
print(y)

0     Grandes
1    Pequenas
2    Pequenas
3      Médias
4     Grandes
5    Pequenas
6     Grandes
7      Médias
Name: Manchas, dtype: object

In [12]:
print("\n--- AS FEATURES (X) ---")
display(X.head(3))

--- AS FEATURES (X) ---

    ID     Nome  Idade Sexo  Peso Temp.  Num. Inter. Estado Diagnóstico
0  123   Marcos     37    M    73  38,0            2     SP      Doente
1  124    Maria     18    F    79  39,5            4     MG    Saudável
2  125  Antônio     40    M    68  38,0            0     RS      Doente

In [13]:
print("\n--- O RÓTULO (y) ---")
display(y.head(3))

--- O RÓTULO (y) ---

0     Grandes
1    Pequenas
2    Pequenas
Name: Manchas, dtype: object